repos:
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.29.0
  hooks:
  - id: yapf
    language: system

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.770
  hooks:
  - id: mypy
    exclude: '^(doc/)|(examples/)|(utils/)'

- repo: local
  hooks:
  - id: prospector
    name: prospector
    entry: prospector
    types: [file, python]
    language: system
    exclude: '^(doc/)|(examples/)'
  - id: version-number
    name: Check version numbers
    entry: python ./utils/validate_version_consistency.py
    language: system
    files: >-
      (?x)^(
        setup.json|
        utils/validate_version_consistency.py|
        aiida_bands_inspect/__init__.py
      )$
    pass_filenames: false
