language: python
python: 2.7
cache: pip
sudo: true
services:
  - postgresql
addons:
  postgresql: "9.5"
before_install:  # copied from pgtest's travis.yml
  - sudo apt-get install locate
  - sudo service postgresql stop
  - sudo apt-get remove postgresql
  - sudo apt-get install postgresql
  - sudo updatedb
install:
  - pip3 install bands-inspect
  - pip install -e git+https://github.com/aiidateam/aiida_core.git#egg=aiida_core
  - pip install -e git+https://github.com/greschd/aiida_pytest#egg=aiida_pytest
  - pip install -e .[dev]
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="tests"
script:
  - ./.travis-data/test_script.sh
