language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
cache: pip
sudo: true
services:
  - rabbitmq
  - postgresql
addons:
  apt:
    packages:
      - python3
      - python3-tk
      - python3-pip
      - python3-numpy
      - python3-scipy
      - python3-matplotlib
      - python3-h5py
      - rabbitmq-server
before_install:
  - sudo service postgresql restart
  - sudo pip3 install -U setuptools
  - sudo pip3 install bands-inspect
  - export MPLBACKEND=Agg
install:
  - pip install -U 'pip<19' wheel setuptools
  - pip install .[dev]
  - reentry scan
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="tests"
script:
  - ./.travis-data/test_script.sh
