language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
sudo: true
services:
  - rabbitmq
  - postgresql
addons:
  apt:
    packages:
      - libhdf5-dev
      - python3
      - python3-tk
      - python3-pip
      - python3-numpy
      - python3-scipy
      - python3-matplotlib
      - python3-h5py
      - rabbitmq-server
env:
  - TEST_TYPE="pre-commit"
    INSTALL_TYPE="dev_precommit"
  - TEST_TYPE="tests"
    INSTALL_TYPE="testing"
  - TEST_TYPE="tests"
    INSTALL_TYPE="testing_sdist"
before_install:
  - sudo service postgresql restart
  - sudo pip3 install -U pip setuptools
  - sudo pip3 install -U matplotlib
  - sudo pip3 install bands-inspect
install:
  - ./.travis-data/install_script.sh
script:
  - ./.travis-data/test_script.sh
