language: python
python:
  - "2.7"
  - "3.6"
cache: pip
sudo: true
services:
  - postgresql
  - rabbitmq
addons:
  apt:
    packages:
      - python3
      - python3-tk
      - python3-pip
      - python3-numpy
      - python3-scipy
      - python3-matplotlib
      - python3-h5py
  postgresql: "9.5"
before_install:
  - sudo pip3 install -U setuptools
  - sudo pip3 install bands-inspect
install:
  - pip install -U 'pip<19' wheel setuptools
  - pip install git+https://github.com/greschd/aiida_pytest@migrate_v1#egg=aiida_pytest
  - pip install .[dev]
env:
  - TEST_TYPE="pre-commit"
  - TEST_TYPE="tests"
script:
  - ./.travis-data/test_script.sh
